### ISSUE TITLE
Support Atom editor setting conversion

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [typescript-eslint/tslint-to-eslint-config#289]
### 🚀 Feature Request

#250 added an `--editor` feature to convert VS Code's TSLint extension settings to the VS Code ESLint equivalents. It'd be lovely to have a similar option for Atom: if a settings file for it exists, it should be converted.

#### Existing Behavior

`tslint-to-eslint-config` only looks for and supports the VS Code syntax for now.

#### Change Proposal

Whatever Atom uses ([this](https://flight-manual.atom.io/using-atom/sections/basic-customization/)?) should be supported as well. If _either_ config file exists, its respective conversion should be attempted.

**Comment by JoshuaKGoldberg** [comment]
Taking a deeper look here, https://github.com/AtomLinter/linter-tslint supports three configuration options:

```yml
'linter-tslint':
  # Custom rules directory (absolute path)
  rulesDirectory: "/path/to/rules"
  # Try using the local tslint package (if exist)
  useLocalTslint: true
  # Enable semantic rules
  enableSemanticRules: true
```

The ESLint equivalent is https://github.com/AtomLinter/linter-eslint, which seems to have the following:

```yml
"linter-eslint":
    advanced:
      disableEslintIgnore: true
      disableFSCache: true
    autofix:
      fixOnSave: true
      ignoreFixableRulesWhileTyping: true
    global:
      useGlobalEslint: true
    lintHtmlFiles: true
```

So, I think the only option shared between them is `useLocalTslint` -> `global.useGlobalEslint` (as opposite values).
